<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class InsertValuesToMasterFilter extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('reports_master_filter', function (Blueprint $table) {
            //
        });
        
        // Open Orders
        DB::table('reports_master_filter')->insert([            
            array('id' => 1, 'report_type' => 'Open Orders', 'ui_name' => 'Channel Order Number', 'column_name' => 'channel_order_number', 'table_name' => 'order_summary'), 
            array('id' => 2, 'report_type' => 'Open Orders', 'ui_name' => 'Order Source', 'column_name' => 'order_source', 'table_name' => 'order_summary'), 
            array('id' => 3, 'report_type' => 'Open Orders', 'ui_name' => 'Channel Type', 'column_name' => 'channel_type', 'table_name' => 'order_summary'), 
            array('id' => 4, 'report_type' => 'Open Orders', 'ui_name' => 'Client Id', 'column_name' => 'client_id', 'table_name' => 'order_summary'), 
            array('id' => 5, 'report_type' => 'Open Orders', 'ui_name' => 'Purchase Date', 'column_name' => 'purchase_date', 'table_name' => 'order_summary'), 
            array('id' => 6, 'report_type' => 'Open Orders', 'ui_name' => 'Customer Number', 'column_name' => 'customer_number', 'table_name' => 'order_summary'), 
            array('id' => 7, 'report_type' => 'Open Orders', 'ui_name' => 'Customer Name', 'column_name' => 'customer_name', 'table_name' => 'order_summary'), 
            array('id' => 8, 'report_type' => 'Open Orders', 'ui_name' => 'Customer Email', 'column_name' => 'customer_email', 'table_name' => 'order_summary'), 
            array('id' => 9, 'report_type' => 'Open Orders', 'ui_name' => 'Customer Phone', 'column_name' => 'customer_phone', 'table_name' => 'order_summary'), 
            array('id' => 10, 'report_type' => 'Open Orders', 'ui_name' => 'Ship to Name', 'column_name' => 'ship_to_name', 'table_name' => 'order_summary'), 
            array('id' => 11, 'report_type' => 'Open Orders', 'ui_name' => 'Ship to Address Type', 'column_name' => 'ship_to_address_type', 'table_name' => 'order_summary'), 
            array('id' => 12, 'report_type' => 'Open Orders', 'ui_name' => 'Ship to Address1', 'column_name' => 'ship_to_address1', 'table_name' => 'order_summary'), 
            array('id' => 13, 'report_type' => 'Open Orders', 'ui_name' => 'Ship to Address2', 'column_name' => 'ship_to_address2', 'table_name' => 'order_summary'), 
            array('id' => 14, 'report_type' => 'Open Orders', 'ui_name' => 'Ship to Address3', 'column_name' => 'ship_to_address3', 'table_name' => 'order_summary'), 
            array('id' => 15, 'report_type' => 'Open Orders', 'ui_name' => 'Ship to City', 'column_name' => 'ship_to_city', 'table_name' => 'order_summary'), 
            array('id' => 16, 'report_type' => 'Open Orders', 'ui_name' => 'Ship to State', 'column_name' => 'ship_to_state', 'table_name' => 'order_summary'), 
            array('id' => 17, 'report_type' => 'Open Orders', 'ui_name' => 'Ship to Zip', 'column_name' => 'ship_to_zip', 'table_name' => 'order_summary'), 
            array('id' => 18, 'report_type' => 'Open Orders', 'ui_name' => 'Ship to Country', 'column_name' => 'ship_to_country', 'table_name' => 'order_summary'), 
            array('id' => 19, 'report_type' => 'Open Orders', 'ui_name' => 'Ship to Phone', 'column_name' => 'ship_to_phone', 'table_name' => 'order_summary'), 
            array('id' => 20, 'report_type' => 'Open Orders', 'ui_name' => 'Shipping Methods', 'column_name' => 'shipping_method', 'table_name' => 'order_summary'), 
            array('id' => 21, 'report_type' => 'Open Orders', 'ui_name' => 'Delivery Notes', 'column_name' => 'delivery_notes', 'table_name' => 'order_summary'), 
            array('id' => 22, 'report_type' => 'Open Orders', 'ui_name' => 'Customer Shipping Price', 'column_name' => 'customer_shipping_price', 'table_name' => 'order_summary'), 
            array('id' => 23, 'report_type' => 'Open Orders', 'ui_name' => 'Gift Message', 'column_name' => 'gift_message', 'table_name' => 'order_summary'), 
            array('id' => 24, 'report_type' => 'Open Orders', 'ui_name' => 'Salex Tax', 'column_name' => 'sales_tax', 'table_name' => 'order_summary'), 
            array('id' => 25, 'report_type' => 'Open Orders', 'ui_name' => 'Shipping Tax', 'column_name' => 'shipping_tax', 'table_name' => 'order_summary'), 
            array('id' => 26, 'report_type' => 'Open Orders', 'ui_name' => 'Shipping Discount Type', 'column_name' => 'shipping_discount_type', 'table_name' => 'order_summary'), 
            array('id' => 27, 'report_type' => 'Open Orders', 'ui_name' => 'Shipping Discount Amount', 'column_name' => 'shipping_discount_amount', 'table_name' => 'order_summary'), 
            array('id' => 28, 'report_type' => 'Open Orders', 'ui_name' => 'Channel Estimated Ship Date', 'column_name' => 'channel_estimated_ship_date', 'table_name' => 'order_summary'), 
            array('id' => 29, 'report_type' => 'Open Orders', 'ui_name' => 'Channel Estimated Delivery Date', 'column_name' => 'channel_estimated_delivery_date', 'table_name' => 'order_summary'), 
            array('id' => 30, 'report_type' => 'Open Orders', 'ui_name' => 'Is Amazon Prime', 'column_name' => 'is_amazon_prime', 'table_name' => 'order_summary'), 
            array('id' => 31, 'report_type' => 'Open Orders', 'ui_name' => 'Paypal Transaction Ids', 'column_name' => 'paypal_transaction_ids', 'table_name' => 'order_summary'), 
            array('id' => 32, 'report_type' => 'Open Orders', 'ui_name' => 'Customer Vat', 'column_name' => 'customer_vat', 'table_name' => 'order_summary'), 
            array('id' => 33, 'report_type' => 'Open Orders', 'ui_name' => 'Currency', 'column_name' => 'currency', 'table_name' => 'order_summary'), 
            array('id' => 34, 'report_type' => 'Open Orders', 'ui_name' => 'Ship by Date', 'column_name' => 'ship_by_date', 'table_name' => 'order_summary'), 
            array('id' => 35, 'report_type' => 'Open Orders', 'ui_name' => 'Order Total Price', 'column_name' => 'order_total_price', 'table_name' => 'order_summary'), 
            array('id' => 36, 'report_type' => 'Open Orders', 'ui_name' => 'Order Status', 'column_name' => 'order_status', 'table_name' => 'order_summary'), 
            array('id' => 37, 'report_type' => 'Open Orders', 'ui_name' => 'Complete Date', 'column_name' => 'complete_date', 'table_name' => 'order_summary')         
        ]);

        // Shipped Orders
        DB::table('reports_master_filter')->insert([            
            array('id' => 38, 'report_type' => 'Shipped Orders', 'ui_name' => 'Etailer Order Number', 'column_name' => 'etailer_order_number', 'table_name' => 'order_summary'),
            array('id' => 39, 'report_type' => 'Shipped Orders', 'ui_name' => 'Channel Order Number', 'column_name' => 'channel_order_number', 'table_name' => 'order_summary'),
            array('id' => 40, 'report_type' => 'Shipped Orders', 'ui_name' => 'Order Source', 'column_name' => 'order_source', 'table_name' => 'order_summary'),
            array('id' => 41, 'report_type' => 'Shipped Orders', 'ui_name' => 'Channel Type', 'column_name' => 'channel_type', 'table_name' => 'order_summary'),
            array('id' => 42, 'report_type' => 'Shipped Orders', 'ui_name' => 'Client Id', 'column_name' => 'client_id', 'table_name' => 'order_summary'),
            array('id' => 43, 'report_type' => 'Shipped Orders', 'ui_name' => 'Purchase Date', 'column_name' => 'purchase_date', 'table_name' => 'order_summary'),
            array('id' => 44, 'report_type' => 'Shipped Orders', 'ui_name' => 'Customer Number', 'column_name' => 'customer_number', 'table_name' => 'order_summary'),
            array('id' => 45, 'report_type' => 'Shipped Orders', 'ui_name' => 'Customer Name', 'column_name' => 'customer_name', 'table_name' => 'order_summary'),
            array('id' => 46, 'report_type' => 'Shipped Orders', 'ui_name' => 'Customer Email', 'column_name' => 'customer_email', 'table_name' => 'order_summary'),
            array('id' => 47, 'report_type' => 'Shipped Orders', 'ui_name' => 'Customer Phone', 'column_name' => 'customer_phone', 'table_name' => 'order_summary'),
            array('id' => 48, 'report_type' => 'Shipped Orders', 'ui_name' => 'Ship To Name', 'column_name' => 'ship_to_name', 'table_name' => 'order_summary'),
            array('id' => 49, 'report_type' => 'Shipped Orders', 'ui_name' => 'Ship To Address Type', 'column_name' => 'ship_to_address_type', 'table_name' => 'order_summary'),
            array('id' => 50, 'report_type' => 'Shipped Orders', 'ui_name' => 'Ship To Address1', 'column_name' => 'ship_to_address1', 'table_name' => 'order_summary'),
            array('id' => 51, 'report_type' => 'Shipped Orders', 'ui_name' => 'Ship To Address2', 'column_name' => 'ship_to_address2', 'table_name' => 'order_summary'),
            array('id' => 52, 'report_type' => 'Shipped Orders', 'ui_name' => 'Ship To Address3', 'column_name' => 'ship_to_address3', 'table_name' => 'order_summary'),
            array('id' => 53, 'report_type' => 'Shipped Orders', 'ui_name' => 'Ship To City', 'column_name' => 'ship_to_city', 'table_name' => 'order_summary'),
            array('id' => 54, 'report_type' => 'Shipped Orders', 'ui_name' => 'Ship To State', 'column_name' => 'ship_to_state', 'table_name' => 'order_summary'),
            array('id' => 55, 'report_type' => 'Shipped Orders', 'ui_name' => 'Ship To Zip', 'column_name' => 'ship_to_zip', 'table_name' => 'order_summary'),
            array('id' => 56, 'report_type' => 'Shipped Orders', 'ui_name' => 'Ship To Country', 'column_name' => 'ship_to_country', 'table_name' => 'order_summary'),
            array('id' => 57, 'report_type' => 'Shipped Orders', 'ui_name' => 'Ship To Phone', 'column_name' => 'ship_to_phone', 'table_name' => 'order_summary'),
            array('id' => 58, 'report_type' => 'Shipped Orders', 'ui_name' => 'Shipping Method', 'column_name' => 'shipping_method', 'table_name' => 'order_summary'),
            array('id' => 59, 'report_type' => 'Shipped Orders', 'ui_name' => 'Delivery Notes', 'column_name' => 'delivery_notes', 'table_name' => 'order_summary'),
            array('id' => 60, 'report_type' => 'Shipped Orders', 'ui_name' => 'Customer Shipping Price', 'column_name' => 'customer_shipping_price', 'table_name' => 'order_summary'),
            array('id' => 61, 'report_type' => 'Shipped Orders', 'ui_name' => 'Gift Message', 'column_name' => 'gift_message', 'table_name' => 'order_summary'),
            array('id' => 62, 'report_type' => 'Shipped Orders', 'ui_name' => 'Sales Tax', 'column_name' => 'sales_tax', 'table_name' => 'order_summary'),
            array('id' => 63, 'report_type' => 'Shipped Orders', 'ui_name' => 'Shipping Tax', 'column_name' => 'shipping_tax', 'table_name' => 'order_summary'),
            array('id' => 64, 'report_type' => 'Shipped Orders', 'ui_name' => 'Shipping Discount Type', 'column_name' => 'shipping_discount_type', 'table_name' => 'order_summary'),
            array('id' => 65, 'report_type' => 'Shipped Orders', 'ui_name' => 'Shipping Discount Amount', 'column_name' => 'shipping_discount_amount', 'table_name' => 'order_summary'),
            array('id' => 66, 'report_type' => 'Shipped Orders', 'ui_name' => 'Channel Estimated Ship Date', 'column_name' => 'channel_estimated_ship_date', 'table_name' => 'order_summary'),
            array('id' => 67, 'report_type' => 'Shipped Orders', 'ui_name' => 'Channel Estimated Delivery Date', 'column_name' => 'channel_estimated_delivery_date', 'table_name' => 'order_summary'),
            array('id' => 68, 'report_type' => 'Shipped Orders', 'ui_name' => 'Is Amazon Prime', 'column_name' => 'is_amazon_prime', 'table_name' => 'order_summary'),
            array('id' => 69, 'report_type' => 'Shipped Orders', 'ui_name' => 'Paypal Transaction Ids', 'column_name' => 'paypal_transaction_ids', 'table_name' => 'order_summary'),
            array('id' => 70, 'report_type' => 'Shipped Orders', 'ui_name' => 'Customer Vat', 'column_name' => 'customer_vat', 'table_name' => 'order_summary'),
            array('id' => 71, 'report_type' => 'Shipped Orders', 'ui_name' => 'Currency', 'column_name' => 'currency', 'table_name' => 'order_summary'),
            array('id' => 72, 'report_type' => 'Shipped Orders', 'ui_name' => 'Ship By Date', 'column_name' => 'ship_by_date', 'table_name' => 'order_summary'),
            array('id' => 73, 'report_type' => 'Shipped Orders', 'ui_name' => 'Order Total Price', 'column_name' => 'order_total_price', 'table_name' => 'order_summary'),
            array('id' => 74, 'report_type' => 'Shipped Orders', 'ui_name' => 'Order Status', 'column_name' => 'order_status', 'table_name' => 'order_summary'),
            array('id' => 75, 'report_type' => 'Shipped Orders', 'ui_name' => 'Complete Date', 'column_name' => 'complete_date', 'table_name' => 'order_summary')
        ]);

        // Inventory
        DB::table('reports_master_filter')->insert([
            array('id' => 76, 'report_type' => 'Inventory', 'ui_name' => 'ETIN', 'column_name' => 'ETIN', 'table_name' => 'master_product'),
            array('id' => 77, 'report_type' => 'Inventory', 'ui_name' => 'Parent ETIN', 'column_name' => 'parent_ETIN', 'table_name' => 'master_product'),
            array('id' => 78, 'report_type' => 'Inventory', 'ui_name' => 'Lobs', 'column_name' => 'lobs', 'table_name' => 'master_product'),
            array('id' => 79, 'report_type' => 'Inventory', 'ui_name' => 'Product Listing Name', 'column_name' => 'product_listing_name', 'table_name' => 'master_product'),
            array('id' => 80, 'report_type' => 'Inventory', 'ui_name' => 'Full Product Desc', 'column_name' => 'full_product_desc', 'table_name' => 'master_product'),
            array('id' => 81, 'report_type' => 'Inventory', 'ui_name' => 'About This Item', 'column_name' => 'about_this_item', 'table_name' => 'master_product'),
            array('id' => 82, 'report_type' => 'Inventory', 'ui_name' => 'Manufacturer', 'column_name' => 'manufacturer', 'table_name' => 'master_product'),
            array('id' => 83, 'report_type' => 'Inventory', 'ui_name' => 'Brand', 'column_name' => 'brand', 'table_name' => 'master_product'),
            array('id' => 84, 'report_type' => 'Inventory', 'ui_name' => 'Flavor', 'column_name' => 'flavor', 'table_name' => 'master_product'),
            array('id' => 85, 'report_type' => 'Inventory', 'ui_name' => 'Product Type', 'column_name' => 'product_type', 'table_name' => 'master_product'),
            array('id' => 86, 'report_type' => 'Inventory', 'ui_name' => 'Unit Size', 'column_name' => 'unit_size', 'table_name' => 'master_product'),
            array('id' => 87, 'report_type' => 'Inventory', 'ui_name' => 'Unit Description', 'column_name' => 'unit_description', 'table_name' => 'master_product'),
            array('id' => 88, 'report_type' => 'Inventory', 'ui_name' => 'Pack Form Count', 'column_name' => 'pack_form_count', 'table_name' => 'master_product'),
            array('id' => 89, 'report_type' => 'Inventory', 'ui_name' => 'Unit In Pack', 'column_name' => 'unit_in_pack', 'table_name' => 'master_product'),
            array('id' => 90, 'report_type' => 'Inventory', 'ui_name' => 'Item Form Description', 'column_name' => 'item_form_description', 'table_name' => 'master_product'),
            array('id' => 91, 'report_type' => 'Inventory', 'ui_name' => 'Total Ounces', 'column_name' => 'total_ounces', 'table_name' => 'master_product'),
            array('id' => 92, 'report_type' => 'Inventory', 'ui_name' => 'Product Category', 'column_name' => 'product_category', 'table_name' => 'master_product'),
            array('id' => 93, 'report_type' => 'Inventory', 'ui_name' => 'Product Subcategory1', 'column_name' => 'product_subcategory1', 'table_name' => 'master_product'),
            array('id' => 94, 'report_type' => 'Inventory', 'ui_name' => 'Product Subcategory2', 'column_name' => 'product_subcategory2', 'table_name' => 'master_product'),
            array('id' => 95, 'report_type' => 'Inventory', 'ui_name' => 'Product Subcategory3', 'column_name' => 'product_subcategory3', 'table_name' => 'master_product'),
            array('id' => 96, 'report_type' => 'Inventory', 'ui_name' => 'Key Product Attributes Diet', 'column_name' => 'key_product_attributes_diet', 'table_name' => 'master_product'),
            array('id' => 97, 'report_type' => 'Inventory', 'ui_name' => 'Product Tags', 'column_name' => 'product_tags', 'table_name' => 'master_product'),
            array('id' => 98, 'report_type' => 'Inventory', 'ui_name' => 'MFG Shelf Life', 'column_name' => 'MFG_shelf_life', 'table_name' => 'master_product'),
            array('id' => 99, 'report_type' => 'Inventory', 'ui_name' => 'Hazardous Materials', 'column_name' => 'hazardous_materials', 'table_name' => 'master_product'),
            array('id' => 100, 'report_type' => 'Inventory', 'ui_name' => 'Storage', 'column_name' => 'storage', 'table_name' => 'master_product'),
            array('id' => 101, 'report_type' => 'Inventory', 'ui_name' => 'Ingredients', 'column_name' => 'ingredients', 'table_name' => 'master_product'),
            array('id' => 102, 'report_type' => 'Inventory', 'ui_name' => 'Allergens', 'column_name' => 'allergens', 'table_name' => 'master_product'),
            array('id' => 103, 'report_type' => 'Inventory', 'ui_name' => 'Prop 65 Flag', 'column_name' => 'prop_65_flag', 'table_name' => 'master_product'),
            array('id' => 104, 'report_type' => 'Inventory', 'ui_name' => 'Prop 65 Ingredient', 'column_name' => 'prop_65_ingredient', 'table_name' => 'master_product'),
            array('id' => 105, 'report_type' => 'Inventory', 'ui_name' => 'Product Temperature', 'column_name' => 'product_temperature', 'table_name' => 'master_product'),
            array('id' => 106, 'report_type' => 'Inventory', 'ui_name' => 'Supplier Product Number', 'column_name' => 'supplier_product_number', 'table_name' => 'master_product'),
            array('id' => 107, 'report_type' => 'Inventory', 'ui_name' => 'Manufacture Product Number', 'column_name' => 'manufacture_product_number', 'table_name' => 'master_product'),
            array('id' => 108, 'report_type' => 'Inventory', 'ui_name' => 'Upc', 'column_name' => 'upc', 'table_name' => 'master_product'),
            array('id' => 109, 'report_type' => 'Inventory', 'ui_name' => 'Gtin', 'column_name' => 'gtin', 'table_name' => 'master_product'),
            array('id' => 110, 'report_type' => 'Inventory', 'ui_name' => 'Asin', 'column_name' => 'asin', 'table_name' => 'master_product'),
            array('id' => 111, 'report_type' => 'Inventory', 'ui_name' => 'GPC Code', 'column_name' => 'GPC_code', 'table_name' => 'master_product'),
            array('id' => 112, 'report_type' => 'Inventory', 'ui_name' => 'GPC Class', 'column_name' => 'GPC_class', 'table_name' => 'master_product'),
            array('id' => 113, 'report_type' => 'Inventory', 'ui_name' => 'HS Code', 'column_name' => 'HS_code', 'table_name' => 'master_product'),
            array('id' => 114, 'report_type' => 'Inventory', 'ui_name' => 'Weight', 'column_name' => 'weight', 'table_name' => 'master_product'),
            array('id' => 115, 'report_type' => 'Inventory', 'ui_name' => 'Dimensional Weight', 'column_name' => 'dimensional_weight', 'table_name' => 'master_product'),
            array('id' => 116, 'report_type' => 'Inventory', 'ui_name' => 'Length', 'column_name' => 'length', 'table_name' => 'master_product'),
            array('id' => 117, 'report_type' => 'Inventory', 'ui_name' => 'Width', 'column_name' => 'width', 'table_name' => 'master_product'),
            array('id' => 118, 'report_type' => 'Inventory', 'ui_name' => 'Height', 'column_name' => 'height', 'table_name' => 'master_product'),
            array('id' => 119, 'report_type' => 'Inventory', 'ui_name' => 'Country Of Origin', 'column_name' => 'country_of_origin', 'table_name' => 'master_product'),
            array('id' => 120, 'report_type' => 'Inventory', 'ui_name' => 'Package Information', 'column_name' => 'package_information', 'table_name' => 'master_product'),
            array('id' => 121, 'report_type' => 'Inventory', 'ui_name' => 'Cost', 'column_name' => 'cost', 'table_name' => 'master_product'),
            array('id' => 122, 'report_type' => 'Inventory', 'ui_name' => 'Acquisition Cost', 'column_name' => 'acquisition_cost', 'table_name' => 'master_product'),
            array('id' => 123, 'report_type' => 'Inventory', 'ui_name' => 'New Cost', 'column_name' => 'new_cost', 'table_name' => 'master_product'),
            array('id' => 124, 'report_type' => 'Inventory', 'ui_name' => 'New Cost Date', 'column_name' => 'new_cost_date', 'table_name' => 'master_product'),
            array('id' => 125, 'report_type' => 'Inventory', 'ui_name' => 'Status', 'column_name' => 'status', 'table_name' => 'master_product'),
            array('id' => 126, 'report_type' => 'Inventory', 'ui_name' => 'Etailer Availability', 'column_name' => 'etailer_availability', 'table_name' => 'master_product'),
            array('id' => 127, 'report_type' => 'Inventory', 'ui_name' => 'Dropship Available', 'column_name' => 'dropship_available', 'table_name' => 'master_product'),
            array('id' => 128, 'report_type' => 'Inventory', 'ui_name' => 'Channel Listing Restrictions', 'column_name' => 'channel_listing_restrictions', 'table_name' => 'master_product'),
            array('id' => 129, 'report_type' => 'Inventory', 'ui_name' => 'POG Flag', 'column_name' => 'POG_flag', 'table_name' => 'master_product'),
            array('id' => 130, 'report_type' => 'Inventory', 'ui_name' => 'Consignment', 'column_name' => 'consignment', 'table_name' => 'master_product'),
            array('id' => 131, 'report_type' => 'Inventory', 'ui_name' => 'Warehouses Assigned', 'column_name' => 'warehouses_assigned', 'table_name' => 'master_product'),
            array('id' => 132, 'report_type' => 'Inventory', 'ui_name' => 'Status Date', 'column_name' => 'status_date', 'table_name' => 'master_product'),
            array('id' => 133, 'report_type' => 'Inventory', 'ui_name' => 'Current Supplier', 'column_name' => 'current_supplier', 'table_name' => 'master_product'),
            array('id' => 134, 'report_type' => 'Inventory', 'ui_name' => 'Supplier Status', 'column_name' => 'supplier_status', 'table_name' => 'master_product'),
            array('id' => 135, 'report_type' => 'Inventory', 'ui_name' => 'Supplier Description', 'column_name' => 'supplier_description', 'table_name' => 'master_product'),
            array('id' => 136, 'report_type' => 'Inventory', 'ui_name' => 'Is Approve', 'column_name' => 'is_approve', 'table_name' => 'master_product'),
            array('id' => 137, 'report_type' => 'Inventory', 'ui_name' => 'Approved Date', 'column_name' => 'approved_date', 'table_name' => 'master_product'),
            array('id' => 138, 'report_type' => 'Inventory', 'ui_name' => 'Is Edit', 'column_name' => 'is_edit', 'table_name' => 'master_product'),
            array('id' => 139, 'report_type' => 'Inventory', 'ui_name' => 'Cancel Reason', 'column_name' => 'cancel_reason', 'table_name' => 'master_product'),
            array('id' => 140, 'report_type' => 'Inventory', 'ui_name' => 'Product Listing ETIN', 'column_name' => 'product_listing_ETIN', 'table_name' => 'master_product'),
            array('id' => 141, 'report_type' => 'Inventory', 'ui_name' => 'Alternate ETINs', 'column_name' => 'alternate_ETINs', 'table_name' => 'master_product'),
            array('id' => 142, 'report_type' => 'Inventory', 'ui_name' => 'Product Edit Request', 'column_name' => 'product_edit_request', 'table_name' => 'master_product'),
            array('id' => 143, 'report_type' => 'Inventory', 'ui_name' => 'Queue Status', 'column_name' => 'queue_status', 'table_name' => 'master_product'),
            array('id' => 144, 'report_type' => 'Inventory', 'ui_name' => 'Updated By', 'column_name' => 'updated_by', 'table_name' => 'master_product'),
            array('id' => 145, 'report_type' => 'Inventory', 'ui_name' => 'Inserted By', 'column_name' => 'inserted_by', 'table_name' => 'master_product'),
            array('id' => 146, 'report_type' => 'Inventory', 'ui_name' => 'Product Subcategory4', 'column_name' => 'product_subcategory4', 'table_name' => 'master_product'),
            array('id' => 147, 'report_type' => 'Inventory', 'ui_name' => 'Product Subcategory5', 'column_name' => 'product_subcategory5', 'table_name' => 'master_product'),
            array('id' => 148, 'report_type' => 'Inventory', 'ui_name' => 'Product Subcategory6', 'column_name' => 'product_subcategory6', 'table_name' => 'master_product'),
            array('id' => 149, 'report_type' => 'Inventory', 'ui_name' => 'Product Subcategory7', 'column_name' => 'product_subcategory7', 'table_name' => 'master_product'),
            array('id' => 150, 'report_type' => 'Inventory', 'ui_name' => 'Product Subcategory8', 'column_name' => 'product_subcategory8', 'table_name' => 'master_product'),
            array('id' => 151, 'report_type' => 'Inventory', 'ui_name' => 'Product Subcategory9', 'column_name' => 'product_subcategory9', 'table_name' => 'master_product'),
            array('id' => 152, 'report_type' => 'Inventory', 'ui_name' => 'Week Worth Qty', 'column_name' => 'week_worth_qty', 'table_name' => 'master_product'),
            array('id' => 153, 'report_type' => 'Inventory', 'ui_name' => 'Min Order Qty', 'column_name' => 'min_order_qty', 'table_name' => 'master_product'),
            array('id' => 154, 'report_type' => 'Inventory', 'ui_name' => 'Chanel Ids', 'column_name' => 'chanel_ids', 'table_name' => 'master_product'),
            array('id' => 155, 'report_type' => 'Inventory', 'ui_name' => 'Lead Time', 'column_name' => 'lead_time', 'table_name' => 'master_product'),
            array('id' => 156, 'report_type' => 'Inventory', 'ui_name' => 'Supplier Type', 'column_name' => 'supplier_type', 'table_name' => 'master_product'),
            array('id' => 157, 'report_type' => 'Inventory', 'ui_name' => 'Aisle Id', 'column_name' => 'aisle_id', 'table_name' => 'master_shelf'),
            array('id' => 158, 'report_type' => 'Inventory', 'ui_name' => 'Bay Id', 'column_name' => 'bay_id', 'table_name' => 'master_shelf'),
            array('id' => 159, 'report_type' => 'Inventory', 'ui_name' => 'Shelf', 'column_name' => 'shelf', 'table_name' => 'master_shelf'),
            array('id' => 160, 'report_type' => 'Inventory', 'ui_name' => 'Slot', 'column_name' => 'slot', 'table_name' => 'master_shelf'),
            array('id' => 161, 'report_type' => 'Inventory', 'ui_name' => 'Address', 'column_name' => 'address', 'table_name' => 'master_shelf'),
            array('id' => 162, 'report_type' => 'Inventory', 'ui_name' => 'Location Type Id', 'column_name' => 'location_type_id', 'table_name' => 'master_shelf'),
            array('id' => 163, 'report_type' => 'Inventory', 'ui_name' => 'Max Qty', 'column_name' => 'max_qty', 'table_name' => 'master_shelf'),
            array('id' => 164, 'report_type' => 'Inventory', 'ui_name' => 'Cur Qty', 'column_name' => 'cur_qty', 'table_name' => 'master_shelf'),
            array('id' => 165, 'report_type' => 'Inventory', 'ui_name' => 'Parent Id', 'column_name' => 'parent_id', 'table_name' => 'master_shelf')
        ]);

        // OOD
        DB::table('reports_master_filter')->insert([
            array('id' => 166, 'report_type' => 'OOD', 'ui_name' => 'ETIN', 'column_name' => 'ETIN', 'table_name' => 'master_product'),
            array('id' => 167, 'report_type' => 'OOD', 'ui_name' => 'Parent ETIN', 'column_name' => 'parent_ETIN', 'table_name' => 'master_product'),
            array('id' => 168, 'report_type' => 'OOD', 'ui_name' => 'Lobs', 'column_name' => 'lobs', 'table_name' => 'master_product'),
            array('id' => 169, 'report_type' => 'OOD', 'ui_name' => 'Product Listing Name', 'column_name' => 'product_listing_name', 'table_name' => 'master_product'),
            array('id' => 170, 'report_type' => 'OOD', 'ui_name' => 'Full Product Desc', 'column_name' => 'full_product_desc', 'table_name' => 'master_product'),
            array('id' => 171, 'report_type' => 'OOD', 'ui_name' => 'About This Item', 'column_name' => 'about_this_item', 'table_name' => 'master_product'),
            array('id' => 172, 'report_type' => 'OOD', 'ui_name' => 'Manufacturer', 'column_name' => 'manufacturer', 'table_name' => 'master_product'),
            array('id' => 173, 'report_type' => 'OOD', 'ui_name' => 'Brand', 'column_name' => 'brand', 'table_name' => 'master_product'),
            array('id' => 174, 'report_type' => 'OOD', 'ui_name' => 'Flavor', 'column_name' => 'flavor', 'table_name' => 'master_product'),
            array('id' => 175, 'report_type' => 'OOD', 'ui_name' => 'Product Type', 'column_name' => 'product_type', 'table_name' => 'master_product'),
            array('id' => 176, 'report_type' => 'OOD', 'ui_name' => 'Unit Size', 'column_name' => 'unit_size', 'table_name' => 'master_product'),
            array('id' => 177, 'report_type' => 'OOD', 'ui_name' => 'Unit Description', 'column_name' => 'unit_description', 'table_name' => 'master_product'),
            array('id' => 178, 'report_type' => 'OOD', 'ui_name' => 'Pack Form Count', 'column_name' => 'pack_form_count', 'table_name' => 'master_product'),
            array('id' => 179, 'report_type' => 'OOD', 'ui_name' => 'Unit In Pack', 'column_name' => 'unit_in_pack', 'table_name' => 'master_product'),
            array('id' => 180, 'report_type' => 'OOD', 'ui_name' => 'Item Form Description', 'column_name' => 'item_form_description', 'table_name' => 'master_product'),
            array('id' => 181, 'report_type' => 'OOD', 'ui_name' => 'Total Ounces', 'column_name' => 'total_ounces', 'table_name' => 'master_product'),
            array('id' => 182, 'report_type' => 'OOD', 'ui_name' => 'Product Category', 'column_name' => 'product_category', 'table_name' => 'master_product'),
            array('id' => 183, 'report_type' => 'OOD', 'ui_name' => 'Product Subcategory1', 'column_name' => 'product_subcategory1', 'table_name' => 'master_product'),
            array('id' => 184, 'report_type' => 'OOD', 'ui_name' => 'Product Subcategory2', 'column_name' => 'product_subcategory2', 'table_name' => 'master_product'),
            array('id' => 185, 'report_type' => 'OOD', 'ui_name' => 'Product Subcategory3', 'column_name' => 'product_subcategory3', 'table_name' => 'master_product'),
            array('id' => 186, 'report_type' => 'OOD', 'ui_name' => 'Key Product Attributes Diet', 'column_name' => 'key_product_attributes_diet', 'table_name' => 'master_product'),
            array('id' => 187, 'report_type' => 'OOD', 'ui_name' => 'Product Tags', 'column_name' => 'product_tags', 'table_name' => 'master_product'),
            array('id' => 188, 'report_type' => 'OOD', 'ui_name' => 'MFG Shelf Life', 'column_name' => 'MFG_shelf_life', 'table_name' => 'master_product'),
            array('id' => 189, 'report_type' => 'OOD', 'ui_name' => 'Hazardous Materials', 'column_name' => 'hazardous_materials', 'table_name' => 'master_product'),
            array('id' => 190, 'report_type' => 'OOD', 'ui_name' => 'Storage', 'column_name' => 'storage', 'table_name' => 'master_product'),
            array('id' => 191, 'report_type' => 'OOD', 'ui_name' => 'Ingredients', 'column_name' => 'ingredients', 'table_name' => 'master_product'),
            array('id' => 192, 'report_type' => 'OOD', 'ui_name' => 'Allergens', 'column_name' => 'allergens', 'table_name' => 'master_product'),
            array('id' => 193, 'report_type' => 'OOD', 'ui_name' => 'Prop 65 Flag', 'column_name' => 'prop_65_flag', 'table_name' => 'master_product'),
            array('id' => 194, 'report_type' => 'OOD', 'ui_name' => 'Prop 65 Ingredient', 'column_name' => 'prop_65_ingredient', 'table_name' => 'master_product'),
            array('id' => 195, 'report_type' => 'OOD', 'ui_name' => 'Product Temperature', 'column_name' => 'product_temperature', 'table_name' => 'master_product'),
            array('id' => 196, 'report_type' => 'OOD', 'ui_name' => 'Supplier Product Number', 'column_name' => 'supplier_product_number', 'table_name' => 'master_product'),
            array('id' => 197, 'report_type' => 'OOD', 'ui_name' => 'Manufacture Product Number', 'column_name' => 'manufacture_product_number', 'table_name' => 'master_product'),
            array('id' => 198, 'report_type' => 'OOD', 'ui_name' => 'Upc', 'column_name' => 'upc', 'table_name' => 'master_product'),
            array('id' => 199, 'report_type' => 'OOD', 'ui_name' => 'Gtin', 'column_name' => 'gtin', 'table_name' => 'master_product'),
            array('id' => 200, 'report_type' => 'OOD', 'ui_name' => 'Asin', 'column_name' => 'asin', 'table_name' => 'master_product'),
            array('id' => 201, 'report_type' => 'OOD', 'ui_name' => 'GPC Code', 'column_name' => 'GPC_code', 'table_name' => 'master_product'),
            array('id' => 202, 'report_type' => 'OOD', 'ui_name' => 'GPC Class', 'column_name' => 'GPC_class', 'table_name' => 'master_product'),
            array('id' => 203, 'report_type' => 'OOD', 'ui_name' => 'HS Code', 'column_name' => 'HS_code', 'table_name' => 'master_product'),
            array('id' => 204, 'report_type' => 'OOD', 'ui_name' => 'Weight', 'column_name' => 'weight', 'table_name' => 'master_product'),
            array('id' => 205, 'report_type' => 'OOD', 'ui_name' => 'Dimensional Weight', 'column_name' => 'dimensional_weight', 'table_name' => 'master_product'),
            array('id' => 206, 'report_type' => 'OOD', 'ui_name' => 'Length', 'column_name' => 'length', 'table_name' => 'master_product'),
            array('id' => 207, 'report_type' => 'OOD', 'ui_name' => 'Width', 'column_name' => 'width', 'table_name' => 'master_product'),
            array('id' => 208, 'report_type' => 'OOD', 'ui_name' => 'Height', 'column_name' => 'height', 'table_name' => 'master_product'),
            array('id' => 209, 'report_type' => 'OOD', 'ui_name' => 'Country Of Origin', 'column_name' => 'country_of_origin', 'table_name' => 'master_product'),
            array('id' => 210, 'report_type' => 'OOD', 'ui_name' => 'Package Information', 'column_name' => 'package_information', 'table_name' => 'master_product'),
            array('id' => 211, 'report_type' => 'OOD', 'ui_name' => 'Cost', 'column_name' => 'cost', 'table_name' => 'master_product'),
            array('id' => 212, 'report_type' => 'OOD', 'ui_name' => 'Acquisition Cost', 'column_name' => 'acquisition_cost', 'table_name' => 'master_product'),
            array('id' => 213, 'report_type' => 'OOD', 'ui_name' => 'New Cost', 'column_name' => 'new_cost', 'table_name' => 'master_product'),
            array('id' => 214, 'report_type' => 'OOD', 'ui_name' => 'New Cost Date', 'column_name' => 'new_cost_date', 'table_name' => 'master_product'),
            array('id' => 215, 'report_type' => 'OOD', 'ui_name' => 'Status', 'column_name' => 'status', 'table_name' => 'master_product'),
            array('id' => 216, 'report_type' => 'OOD', 'ui_name' => 'Etailer Availability', 'column_name' => 'etailer_availability', 'table_name' => 'master_product'),
            array('id' => 217, 'report_type' => 'OOD', 'ui_name' => 'Dropship Available', 'column_name' => 'dropship_available', 'table_name' => 'master_product'),
            array('id' => 218, 'report_type' => 'OOD', 'ui_name' => 'Channel Listing Restrictions', 'column_name' => 'channel_listing_restrictions', 'table_name' => 'master_product'),
            array('id' => 219, 'report_type' => 'OOD', 'ui_name' => 'POG Flag', 'column_name' => 'POG_flag', 'table_name' => 'master_product'),
            array('id' => 220, 'report_type' => 'OOD', 'ui_name' => 'Consignment', 'column_name' => 'consignment', 'table_name' => 'master_product'),
            array('id' => 221, 'report_type' => 'OOD', 'ui_name' => 'Warehouses Assigned', 'column_name' => 'warehouses_assigned', 'table_name' => 'master_product'),
            array('id' => 222, 'report_type' => 'OOD', 'ui_name' => 'Status Date', 'column_name' => 'status_date', 'table_name' => 'master_product'),
            array('id' => 223, 'report_type' => 'OOD', 'ui_name' => 'Current Supplier', 'column_name' => 'current_supplier', 'table_name' => 'master_product'),
            array('id' => 224, 'report_type' => 'OOD', 'ui_name' => 'Supplier Status', 'column_name' => 'supplier_status', 'table_name' => 'master_product'),
            array('id' => 225, 'report_type' => 'OOD', 'ui_name' => 'Supplier Description', 'column_name' => 'supplier_description', 'table_name' => 'master_product'),
            array('id' => 226, 'report_type' => 'OOD', 'ui_name' => 'Is Approve', 'column_name' => 'is_approve', 'table_name' => 'master_product'),
            array('id' => 227, 'report_type' => 'OOD', 'ui_name' => 'Approved Date', 'column_name' => 'approved_date', 'table_name' => 'master_product'),
            array('id' => 228, 'report_type' => 'OOD', 'ui_name' => 'Is Edit', 'column_name' => 'is_edit', 'table_name' => 'master_product'),
            array('id' => 229, 'report_type' => 'OOD', 'ui_name' => 'Cancel Reason', 'column_name' => 'cancel_reason', 'table_name' => 'master_product'),
            array('id' => 230, 'report_type' => 'OOD', 'ui_name' => 'Product Listing ETIN', 'column_name' => 'product_listing_ETIN', 'table_name' => 'master_product'),
            array('id' => 231, 'report_type' => 'OOD', 'ui_name' => 'Alternate ETINs', 'column_name' => 'alternate_ETINs', 'table_name' => 'master_product'),
            array('id' => 232, 'report_type' => 'OOD', 'ui_name' => 'Product Edit Request', 'column_name' => 'product_edit_request', 'table_name' => 'master_product'),
            array('id' => 233, 'report_type' => 'OOD', 'ui_name' => 'Queue Status', 'column_name' => 'queue_status', 'table_name' => 'master_product'),
            array('id' => 234, 'report_type' => 'OOD', 'ui_name' => 'Updated By', 'column_name' => 'updated_by', 'table_name' => 'master_product'),
            array('id' => 235, 'report_type' => 'OOD', 'ui_name' => 'Inserted By', 'column_name' => 'inserted_by', 'table_name' => 'master_product'),
            array('id' => 236, 'report_type' => 'OOD', 'ui_name' => 'Product Subcategory4', 'column_name' => 'product_subcategory4', 'table_name' => 'master_product'),
            array('id' => 237, 'report_type' => 'OOD', 'ui_name' => 'Product Subcategory5', 'column_name' => 'product_subcategory5', 'table_name' => 'master_product'),
            array('id' => 238, 'report_type' => 'OOD', 'ui_name' => 'Product Subcategory6', 'column_name' => 'product_subcategory6', 'table_name' => 'master_product'),
            array('id' => 239, 'report_type' => 'OOD', 'ui_name' => 'Product Subcategory7', 'column_name' => 'product_subcategory7', 'table_name' => 'master_product'),
            array('id' => 240, 'report_type' => 'OOD', 'ui_name' => 'Product Subcategory8', 'column_name' => 'product_subcategory8', 'table_name' => 'master_product'),
            array('id' => 241, 'report_type' => 'OOD', 'ui_name' => 'Product Subcategory9', 'column_name' => 'product_subcategory9', 'table_name' => 'master_product'),
            array('id' => 242, 'report_type' => 'OOD', 'ui_name' => 'Week Worth Qty', 'column_name' => 'week_worth_qty', 'table_name' => 'master_product'),
            array('id' => 243, 'report_type' => 'OOD', 'ui_name' => 'Min Order Qty', 'column_name' => 'min_order_qty', 'table_name' => 'master_product'),
            array('id' => 244, 'report_type' => 'OOD', 'ui_name' => 'Chanel Ids', 'column_name' => 'chanel_ids', 'table_name' => 'master_product'),
            array('id' => 245, 'report_type' => 'OOD', 'ui_name' => 'Lead Time', 'column_name' => 'lead_time', 'table_name' => 'master_product'),
            array('id' => 246, 'report_type' => 'OOD', 'ui_name' => 'Supplier Type', 'column_name' => 'supplier_type', 'table_name' => 'master_product'),
            array('id' => 247, 'report_type' => 'OOD', 'ui_name' => 'Address', 'column_name' => 'address', 'table_name' => 'expiration_lot_management'),
            array('id' => 248, 'report_type' => 'OOD', 'ui_name' => 'Warehouse Id', 'column_name' => 'warehouse_id', 'table_name' => 'expiration_lot_management'),
            array('id' => 249, 'report_type' => 'OOD', 'ui_name' => 'Qty Delivered', 'column_name' => 'qty_delivered', 'table_name' => 'expiration_lot_management'),
            array('id' => 250, 'report_type' => 'OOD', 'ui_name' => 'Qty Current', 'column_name' => 'qty_current', 'table_name' => 'expiration_lot_management'),
            array('id' => 251, 'report_type' => 'OOD', 'ui_name' => 'Received Date', 'column_name' => 'received_date', 'table_name' => 'expiration_lot_management'),
            array('id' => 252, 'report_type' => 'OOD', 'ui_name' => 'Expiration Date', 'column_name' => 'expiration_date', 'table_name' => 'expiration_lot_management'),
            array('id' => 253, 'report_type' => 'OOD', 'ui_name' => 'Production Date', 'column_name' => 'production_date', 'table_name' => 'expiration_lot_management'),
            array('id' => 254, 'report_type' => 'OOD', 'ui_name' => 'Lot Id', 'column_name' => 'lot_id', 'table_name' => 'expiration_lot_management')
        ]);

        // Shipped Items
        DB::table('reports_master_filter')->insert([
            array('id' => 255, 'report_type' => 'Shipped Items', 'ui_name' => 'Etailer Order Number', 'column_name' => 'etailer_order_number', 'table_name' => 'order_summary'),
            array('id' => 256, 'report_type' => 'Shipped Items', 'ui_name' => 'Channel Order Number', 'column_name' => 'channel_order_number', 'table_name' => 'order_summary'),
            array('id' => 257, 'report_type' => 'Shipped Items', 'ui_name' => 'Order Source', 'column_name' => 'order_source', 'table_name' => 'order_summary'),
            array('id' => 258, 'report_type' => 'Shipped Items', 'ui_name' => 'Channel Type', 'column_name' => 'channel_type', 'table_name' => 'order_summary'),
            array('id' => 259, 'report_type' => 'Shipped Items', 'ui_name' => 'Client Id', 'column_name' => 'client_id', 'table_name' => 'order_summary'),
            array('id' => 260, 'report_type' => 'Shipped Items', 'ui_name' => 'Purchase Date', 'column_name' => 'purchase_date', 'table_name' => 'order_summary'),
            array('id' => 261, 'report_type' => 'Shipped Items', 'ui_name' => 'Customer Number', 'column_name' => 'customer_number', 'table_name' => 'order_summary'),
            array('id' => 262, 'report_type' => 'Shipped Items', 'ui_name' => 'Customer Name', 'column_name' => 'customer_name', 'table_name' => 'order_summary'),
            array('id' => 263, 'report_type' => 'Shipped Items', 'ui_name' => 'Customer Email', 'column_name' => 'customer_email', 'table_name' => 'order_summary'),
            array('id' => 264, 'report_type' => 'Shipped Items', 'ui_name' => 'Customer Phone', 'column_name' => 'customer_phone', 'table_name' => 'order_summary'),
            array('id' => 265, 'report_type' => 'Shipped Items', 'ui_name' => 'Ship To Name', 'column_name' => 'ship_to_name', 'table_name' => 'order_summary'),
            array('id' => 266, 'report_type' => 'Shipped Items', 'ui_name' => 'Ship To Address Type', 'column_name' => 'ship_to_address_type', 'table_name' => 'order_summary'),
            array('id' => 267, 'report_type' => 'Shipped Items', 'ui_name' => 'Ship To Address1', 'column_name' => 'ship_to_address1', 'table_name' => 'order_summary'),
            array('id' => 268, 'report_type' => 'Shipped Items', 'ui_name' => 'Ship To Address2', 'column_name' => 'ship_to_address2', 'table_name' => 'order_summary'),
            array('id' => 269, 'report_type' => 'Shipped Items', 'ui_name' => 'Ship To Address3', 'column_name' => 'ship_to_address3', 'table_name' => 'order_summary'),
            array('id' => 270, 'report_type' => 'Shipped Items', 'ui_name' => 'Ship To City', 'column_name' => 'ship_to_city', 'table_name' => 'order_summary'),
            array('id' => 271, 'report_type' => 'Shipped Items', 'ui_name' => 'Ship To State', 'column_name' => 'ship_to_state', 'table_name' => 'order_summary'),
            array('id' => 272, 'report_type' => 'Shipped Items', 'ui_name' => 'Ship To Zip', 'column_name' => 'ship_to_zip', 'table_name' => 'order_summary'),
            array('id' => 273, 'report_type' => 'Shipped Items', 'ui_name' => 'Ship To Country', 'column_name' => 'ship_to_country', 'table_name' => 'order_summary'),
            array('id' => 274, 'report_type' => 'Shipped Items', 'ui_name' => 'Ship To Phone', 'column_name' => 'ship_to_phone', 'table_name' => 'order_summary'),
            array('id' => 275, 'report_type' => 'Shipped Items', 'ui_name' => 'Shipping Method', 'column_name' => 'shipping_method', 'table_name' => 'order_summary'),
            array('id' => 276, 'report_type' => 'Shipped Items', 'ui_name' => 'Delivery Notes', 'column_name' => 'delivery_notes', 'table_name' => 'order_summary'),
            array('id' => 277, 'report_type' => 'Shipped Items', 'ui_name' => 'Customer Shipping Price', 'column_name' => 'customer_shipping_price', 'table_name' => 'order_summary'),
            array('id' => 278, 'report_type' => 'Shipped Items', 'ui_name' => 'Gift Message', 'column_name' => 'gift_message', 'table_name' => 'order_summary'),
            array('id' => 279, 'report_type' => 'Shipped Items', 'ui_name' => 'Sales Tax', 'column_name' => 'sales_tax', 'table_name' => 'order_summary'),
            array('id' => 280, 'report_type' => 'Shipped Items', 'ui_name' => 'Shipping Tax', 'column_name' => 'shipping_tax', 'table_name' => 'order_summary'),
            array('id' => 281, 'report_type' => 'Shipped Items', 'ui_name' => 'Shipping Discount Type', 'column_name' => 'shipping_discount_type', 'table_name' => 'order_summary'),
            array('id' => 282, 'report_type' => 'Shipped Items', 'ui_name' => 'Shipping Discount Amount', 'column_name' => 'shipping_discount_amount', 'table_name' => 'order_summary'),
            array('id' => 283, 'report_type' => 'Shipped Items', 'ui_name' => 'Channel Estimated Ship Date', 'column_name' => 'channel_estimated_ship_date', 'table_name' => 'order_summary'),
            array('id' => 284, 'report_type' => 'Shipped Items', 'ui_name' => 'Channel Estimated Delivery Date', 'column_name' => 'channel_estimated_delivery_date', 'table_name' => 'order_summary'),
            array('id' => 285, 'report_type' => 'Shipped Items', 'ui_name' => 'Is Amazon Prime', 'column_name' => 'is_amazon_prime', 'table_name' => 'order_summary'),
            array('id' => 286, 'report_type' => 'Shipped Items', 'ui_name' => 'Paypal Transaction Ids', 'column_name' => 'paypal_transaction_ids', 'table_name' => 'order_summary'),
            array('id' => 287, 'report_type' => 'Shipped Items', 'ui_name' => 'Customer Vat', 'column_name' => 'customer_vat', 'table_name' => 'order_summary'),
            array('id' => 288, 'report_type' => 'Shipped Items', 'ui_name' => 'Currency', 'column_name' => 'currency', 'table_name' => 'order_summary'),
            array('id' => 289, 'report_type' => 'Shipped Items', 'ui_name' => 'Ship By Date', 'column_name' => 'ship_by_date', 'table_name' => 'order_summary'),
            array('id' => 290, 'report_type' => 'Shipped Items', 'ui_name' => 'Order Total Price', 'column_name' => 'order_total_price', 'table_name' => 'order_summary'),
            array('id' => 291, 'report_type' => 'Shipped Items', 'ui_name' => 'Order Status', 'column_name' => 'order_status', 'table_name' => 'order_summary'),
            array('id' => 292, 'report_type' => 'Shipped Items', 'ui_name' => 'Complete Date', 'column_name' => 'complete_date', 'table_name' => 'order_summary'),
            array('id' => 293, 'report_type' => 'Shipped Items', 'ui_name' => 'Order Number', 'column_name' => 'order_number', 'table_name' => 'order_details'),
            array('id' => 294, 'report_type' => 'Shipped Items', 'ui_name' => 'ETIN', 'column_name' => 'ETIN', 'table_name' => 'order_details'),
            array('id' => 295, 'report_type' => 'Shipped Items', 'ui_name' => 'SA Line Number', 'column_name' => 'SA_line_number', 'table_name' => 'order_details'),
            array('id' => 296, 'report_type' => 'Shipped Items', 'ui_name' => 'SA Sku', 'column_name' => 'SA_sku', 'table_name' => 'order_details'),
            array('id' => 297, 'report_type' => 'Shipped Items', 'ui_name' => 'Channel Product Name', 'column_name' => 'channel_product_name', 'table_name' => 'order_details'),
            array('id' => 298, 'report_type' => 'Shipped Items', 'ui_name' => 'Etailer Product Name', 'column_name' => 'etailer_product_name', 'table_name' => 'order_details'),
            array('id' => 299, 'report_type' => 'Shipped Items', 'ui_name' => 'Channel Unit Price', 'column_name' => 'channel_unit_price', 'table_name' => 'order_details'),
            array('id' => 300, 'report_type' => 'Shipped Items', 'ui_name' => 'Channel Extended Price', 'column_name' => 'channel_extended_price', 'table_name' => 'order_details'),
            array('id' => 301, 'report_type' => 'Shipped Items', 'ui_name' => 'Etailer Channel Price', 'column_name' => 'etailer_channel_price', 'table_name' => 'order_details'),
            array('id' => 302, 'report_type' => 'Shipped Items', 'ui_name' => 'Discount Name', 'column_name' => 'discount_name', 'table_name' => 'order_details'),
            array('id' => 303, 'report_type' => 'Shipped Items', 'ui_name' => 'Customer Discount', 'column_name' => 'customer_discount', 'table_name' => 'order_details'),
            array('id' => 304, 'report_type' => 'Shipped Items', 'ui_name' => 'Customer Paid Price', 'column_name' => 'customer_paid_price', 'table_name' => 'order_details'),
            array('id' => 305, 'report_type' => 'Shipped Items', 'ui_name' => 'Quantity Ordered', 'column_name' => 'quantity_ordered', 'table_name' => 'order_details'),
            array('id' => 306, 'report_type' => 'Shipped Items', 'ui_name' => 'Quantity Fulfilled', 'column_name' => 'quantity_fulfilled', 'table_name' => 'order_details'),
            array('id' => 307, 'report_type' => 'Shipped Items', 'ui_name' => 'ETIN Flag', 'column_name' => 'ETIN_flag', 'table_name' => 'order_details'),
            array('id' => 308, 'report_type' => 'Shipped Items', 'ui_name' => 'Sub Order Number', 'column_name' => 'sub_order_number', 'table_name' => 'order_details'),
            array('id' => 309, 'report_type' => 'Shipped Items', 'ui_name' => 'Warehouse', 'column_name' => 'warehouse', 'table_name' => 'order_details'),
            array('id' => 310, 'report_type' => 'Shipped Items', 'ui_name' => 'Fulfilled By', 'column_name' => 'fulfilled_by', 'table_name' => 'order_details'),
            array('id' => 311, 'report_type' => 'Shipped Items', 'ui_name' => 'Picker Id', 'column_name' => 'picker_id', 'table_name' => 'order_details'),
            array('id' => 312, 'report_type' => 'Shipped Items', 'ui_name' => 'Status', 'column_name' => 'status', 'table_name' => 'order_details'),
            array('id' => 313, 'report_type' => 'Shipped Items', 'ui_name' => 'Carrier Id', 'column_name' => 'carrier_id', 'table_name' => 'order_details'),
            array('id' => 314, 'report_type' => 'Shipped Items', 'ui_name' => 'Carrier Account Id', 'column_name' => 'carrier_account_id', 'table_name' => 'order_details'),
            array('id' => 315, 'report_type' => 'Shipped Items', 'ui_name' => 'Service Type Id', 'column_name' => 'service_type_id', 'table_name' => 'order_details'),
            array('id' => 316, 'report_type' => 'Shipped Items', 'ui_name' => 'Transit Days', 'column_name' => 'transit_days', 'table_name' => 'order_details')
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('reports_master_filter', function (Blueprint $table) {
            //
        });
    }
}
